### ISSUE TITLE
License of the Artwork?

### ISSUE THREAD

**Issue by hellerbarde** [cg433n/emacs-yosemite-icon#1]
Hi, I am looking for a nice emacs icon to use in a public project. How is your artwork licensed?

Thanks,
hellerbarde

**Comment by cg433n** [comment]
It's licensed under GPL.

**Comment by hellerbarde** [comment]
Thank you very much.

**Comment by cg433n** [comment]
Can you let me know where you're using the icon?

**Comment by hellerbarde** [comment]
For sure! I meant to put it in the previous message, but I was on the phone. It's here, credits and all :+1: https://plus.google.com/108840863190686221561/posts

**Comment by cg433n** [comment]
Thanks!
